DROP_MOVIES_TABLE = '''
    DROP TABLE IF EXISTS MOVIES
'''

DROP_PROJECTIONS_TABLE = '''
    DROP TABLE IF EXISTS PROJECTIONS
'''

DROP_USERS_TABLE = '''
    DROP TABLE IF EXISTS USERS
'''

DROP_RESERVATIONS_TABLE = '''
    DROP TABLE IF EXISTS RESERVATIONS
'''

CREATE_MOVIES_TABLE = '''
    CREATE TABLE IF NOT EXISTS MOVIES (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        NAME TEXT NOT NULL,
        RATING REAL
    )
'''

CREATE_PROJECTIONS_TABLE = '''
    CREATE TABLE IF NOT EXISTS PROJECTIONS (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        MOVIE_ID INTEGER NOT NULL,
        TYPE TEXT NOT NULL,
        DATE_ TEXT NOT NULL,
        TIME_ TEXT NOT NULL,
        FOREIGN KEY(MOVIE_ID) REFERENCES MOVIES(ID)
    )
'''

CREATE_USERS_TABLE = '''
    CREATE TABLE IF NOT EXISTS USERS (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        USERNAME TEXT NOT NULL,
        PASSWORD TEXT NOT NULL,
        LOGGED INTEGER DEFAULT 0
    )
'''

CREATE_RESERVATIONS_TABLE = '''
    CREATE TABLE IF NOT EXISTS RESERVATIONS (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        USER_ID INTEGER NOT NULL,
        PROJECTION_ID INTEGER NOT NULL,
        ROW INTEGER NOT NULL,
        COL INTEGER NOT NULL,
        FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
        FOREIGN KEY(PROJECTION_ID) REFERENCES PROJECTION(ID)
    )
'''

INSERT_MOVIES = '''
    INSERT INTO MOVIES (NAME, RATING)
    VALUES(?, ?)
'''

INSERT_PROJECTIONS = '''
    INSERT INTO PROJECTIONS (MOVIE_ID, TYPE, DATE_, TIME_)
    VALUES (?, ?, ?, ?)
'''

INSERT_RESERVATIONS = '''
    INSERT INTO RESERVATIONS (USER_ID, PROJECTION_ID, ROW, COL)
    VALUES (?, ?, ?, ?)
'''

INSERT_USERS = '''
    INSERT INTO USERS (USERNAME, PASSWORD)
    VALUES (?, ?)
'''
